// Generated by CoffeeScript 1.9.3
(function() {
  var Bus, bus, pub;

  Bus = require('../../brov-bus/');

  bus = new Bus('zmq', 'blueROV-bus');

  pub = bus.registerPublisher();

  bus.registerSubscriber((function(msg) {
    return console.log("No filter: " + (msg.toString()));
  }));

  bus.registerSubscriber((function(msg) {
    return console.log("TEST filter: " + (msg.toString()));
  }), ["TEST"]);

  bus.registerSubscriber((function(msg) {
    return console.log("TEST/TOTO filter: " + (msg.toString()));
  }), ["TEST", "TOTO"]);

  bus.registerSubscriber((function(msg) {
    return console.log("TOTO filter: " + (msg.toString()));
  }), ["TOTO"]);

  pub.send("TEST 1");

  pub.send("TOTO 2");

  pub.send("TITI 3");

}).call(this);
