// Generated by CoffeeScript 1.9.3
(function() {
  var Bus, bus, i, pub;

  try {
    Bus = require('@jilpi/brov-bus');
  } catch (_error) {
    Bus = require('../../brov-bus');
  }

  bus = new Bus('zmq', 'blueROV-bus');

  pub = bus.registerPublisher();

  bus.registerSubscriber((function(msg) {
    return console.log("No filter: " + (msg.toString()));
  }));

  bus.registerSubscriber((function(msg) {
    return console.log("TEST filter: " + (msg.toString()));
  }), ["TEST"]);

  bus.registerSubscriber((function(msg) {
    return console.log("TEST/TOTO filter: " + (msg.toString()));
  }), ["TEST", "TOTO"]);

  bus.registerSubscriber((function(msg) {
    return console.log("TOTO filter: " + (msg.toString()));
  }), ["TOTO"]);

  console.log("send messages in a loop");

  i = 0;

  setInterval(function() {
    pub.send("TEST", i++);
    pub.send("TOTO", i++);
    pub.send("TITI", i++);
    pub.send("", i++);
  }, 2000);

}).call(this);
